"""Added model column to ChatEntry

Revision ID: 09bcbe246cc2
Revises: 69d9c8c033ba
Create Date: 2023-12-10 17:12:39.474735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bcbe246cc2'
down_revision: Union[str, None] = '69d9c8c033ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_entries', sa.Column('model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_entries', 'model')
    # ### end Alembic commands ###
